import { Flowbite, ThemeModeScript } from "flowbite-react";
import { Inter } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import { flowbiteTheme } from "./theme";
import Wallet from "../context/connectwalletcontext";
import HuddleContext from "../context/huddle01context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sol EcoWaifu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/sol-ecowaifu.png" sizes="any" />
        <ThemeModeScript />
      </head>
      <body className={twMerge("bg-gray-50 dark:bg-gray-900", inter.className)}>
        <Wallet>
          <HuddleContext>

            <Flowbite theme={{ theme: flowbiteTheme }}>{children}</Flowbite>
          </HuddleContext>
        </Wallet>
      </body>
    </html>
  );
}
