"use client";
import { waifu } from "../../provider/waifuprovider.js";
import {
  Accordion,
  Alert,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  Card,
  Carousel,
  Checkbox,
  Dropdown,
  Footer,
  Label,
  ListGroup,
  Modal,
  Navbar,
  Pagination,
  Progress,
  Rating,
  Sidebar,
  Spinner,
  Table,
  Tabs,
  TextInput,
  Timeline,
  Toast,
  Tooltip,
} from "flowbite-react";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import {
  BsDribbble,
  BsFacebook,
  BsGithub,
  BsInstagram,
  BsTwitter,
} from "react-icons/bs";
import {
  HiAdjustments,
  HiArrowNarrowRight,
  HiArrowSmRight,
  HiChartPie,
  HiCheck,
  HiClipboardList,
  HiCloudDownload,
  HiDatabase,
  HiExclamation,
  HiEye,
  HiHome,
  HiInbox,
  HiOutlineAdjustments,
  HiShoppingBag,
  HiTable,
  HiUser,
  HiUserCircle,
  HiViewBoards,
  HiX,
} from "react-icons/hi";


export const HomePageContent = function () {
    useEffect(() => {
    }, []);

  return (
    <div className="p-6">
      <section>
        <header>
          <h2 className="mb-3 text-4xl font-bold dark:text-gray-200 text-black">NFTs earned</h2>
        </header>
        <AlertsExample />
        <header>
          <h2 className="mb-3 mt-9 text-xl dark:text-gray-200 text-black">
            EcoWaifu Level<span className="font-bold text-2xl "> 35</span>
          </h2>
        </header>
        <ProgressExample />
      </section>
      
      <section className="mt-8">
        <CardList />
      </section>
    </div>
  );
};

const AlertsExample = function () {
  return (
    <Alert
      color="info"
      rounded={true}
      onDismiss={console.log}
      additionalContent={
        <React.Fragment>
          <div className="mb-4 mt-2 text-sm text-black dark:text-blue-800 font-bold">
            This page contains your Waifus that are generated by EcoWaifu.
          </div>
          <div className="flex">
            <button
              type="button"
              className="mr-2 inline-flex items-center rounded-lg bg-blue-700 px-3 py-1.5 text-center text-xs font-medium text-white hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-800 dark:hover:bg-blue-900"
            >
              <HiEye className="-ml-0.5 mr-2 h-4 w-4" />
              View more
            </button>
            <button
              type="button"
              className="rounded-lg border border-blue-700 bg-transparent px-3 py-1.5 text-center text-xs font-medium text-blue-700 hover:bg-blue-800 hover:text-white focus:ring-4 focus:ring-blue-300 dark:border-blue-800 dark:text-blue-800 dark:hover:text-white"
            >
              Dismiss
            </button>
          </div>
        </React.Fragment>
      }
    >
      <h2 className="text-xl font-bold text-black dark:text-blue-800">
        What is this page?
      </h2>
    </Alert>
  );
};





const CardList = () => {
  const card = waifu;
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      {card.map((waifu) => (
        <a href="/waifu-chat" className="max-w-xs bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-800 dark:border-gray-700 transition duration-300 ease-in-out hover:shadow-lg" key={waifu.imgSrc}>
          <div className="w-full overflow-hidden" style={{ height: '260px' }}>
            <img className="w-full h-full object-cover transform transition duration-300 ease-in-out hover:scale-110" src={waifu.imgSrc} alt={waifu.title} />
          </div>
          <div className="p-5">
            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{waifu.title}</h5>
            <p className="mb-5 font-normal text-gray-700 dark:text-gray-400">Last sale: {waifu.lastSale}</p>
            <div className="flex justify-end ">
              <span className="text-sm bg-blue-200 text-blue-800 font-semibold py-1 px-3 rounded-full">{waifu.price}</span>
            </div>
          </div>
        </a>
      ))}
    </div>
  );
};


const ProgressExample = function () {
  return (
    <Progress
      labelProgress
      progress={45}
      textLabelPosition="outside"
      size="lg"
      color="green"
    />
  );
};

const NFTMinting = function () {
  const [isOpen, setOpen] = useState(false);
  
  return (
    <>
      <Button onClick={() => setOpen(true)}>Mint your NFT now</Button>
      <Modal show={isOpen} onClose={() => setOpen(false)}>
        <Modal.Header>
        Purchase Confirmation
        </Modal.Header>
        <Modal.Body>
          <div className="space-y-6">
            <p className="text-base leading-relaxed text-gray-500 dark:text-gray-400">
              
              {"Mint item for " + 0.00028 + " SOL"}
            </p>
          </div>
        </Modal.Body>
        <Modal.Footer className="flex justify-center align-middle">
          <Button onClick={() => {
            productPrice = 0.00012;
            sendSol;
            setOpen(false)
          }}>Yes</Button>
          <Button color="gray" onClick={() => setOpen(false)}>
            Cancel
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  )
};